# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6998d1671574ed85834d92396515de60c47599335dee2803b7aac734ce7ee5151eeaf79dc4b73e32697ee99a6a3b6fb1c7391c2b8b8b191bf21575e2e45efc38

test:
  secret_key_base: cc44aca649943d35e9fe3f17d3ceed8e74e3955c6c7242b88166b96d3e14bc9867ed6710ce34a876724b9b38af27e16b0b80d88b0e51fb9f3d3e85eada381e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
